import type { ClassStats } from "../types";

export const CLASS_APPEARANCE: Record<string, { bodyId: number; headId: number }> = {
  WARRIOR: { bodyId: 40, headId: 1 },
  MAGE: { bodyId: 22, headId: 3 },
  RANGER: { bodyId: 60, headId: 2 },
  ROGUE: { bodyId: 45, headId: 4 },
  CLERIC: { bodyId: 50, headId: 5 },
  PALADIN: { bodyId: 38, headId: 6 },
  NECROMANCER: { bodyId: 35, headId: 7 },
  DRUID: { bodyId: 70, headId: 8 },
};

export const CLASS_STATS: Record<string, ClassStats> = {
  WARRIOR: {
    hp: 240,
    mana: 60,
    str: 25,
    agi: 12,
    int: 6,
    speedTilesPerSecond: 7,
    attackRange: 1,
    attackCooldownMs: 450,
    attackWindupMs: 120,
    armor: 10,
    maxCompanions: 1,
    // Q: war_cry | W: shield_bash | E: whirlwind | R: battle_shout | T: leap | Y: execute | U: cleave | I: berserker_rage
    abilities: [
      "war_cry",
      "shield_bash",
      "whirlwind",
      "battle_shout",
      "leap",
      "execute",
      "cleave",
      "berserker_rage",
      "shield_wall",
    ],
  },
  MAGE: {
    hp: 140,
    mana: 160,
    str: 6,
    agi: 10,
    int: 28,
    speedTilesPerSecond: 7,
    attackRange: 1,
    attackCooldownMs: 650,
    attackWindupMs: 120,
    armor: 2,
    maxCompanions: 1,
    // fireball | ice_bolt | thunderstorm | blink | mana_shield | frost_nova | elemental_infusion | arcane_surge | spell_echo | meteor_strike | chain_lightning
    abilities: [
      "fireball",
      "ice_bolt",
      "thunderstorm",
      "blink",
      "mana_shield",
      "frost_nova",
      "elemental_infusion",
      "arcane_surge",
      "spell_echo",
      "meteor_strike",
      "chain_lightning",
      "mana_spring",
      "polymorph",
    ],
  },
  RANGER: {
    hp: 160,
    mana: 90,
    str: 10,
    agi: 26,
    int: 10,
    speedTilesPerSecond: 7,
    attackRange: 5,
    attackCooldownMs: 500,
    attackWindupMs: 100,
    armor: 5,
    maxCompanions: 3,
    // Q: multi_shot (AoE) | W: poison_arrow (DoT) | E: evasion (buff) | R: aimed_shot (nuke) | T: mark_target (debuff)
    abilities: [
      "multi_shot",
      "poison_arrow",
      "evasion",
      "aimed_shot",
      "mark_target",
      "pet_bond",
      "explosive_trap",
      "eagle_eye",
      "barrage",
    ],
  },
  ROGUE: {
    hp: 150,
    mana: 80,
    str: 14,
    agi: 24,
    int: 8,
    speedTilesPerSecond: 8,
    attackRange: 1,
    attackCooldownMs: 350,
    attackWindupMs: 80,
    armor: 4,
    maxCompanions: 1,
    // Q: backstab (nuke) | W: stealth | E: envenom (DoT) | R: smoke_bomb (AoE stun) | T: hemorrhage (leech)
    abilities: [
      "backstab",
      "stealth",
      "envenom",
      "smoke_bomb",
      "hemorrhage",
      "shadowstep",
      "pickpocket",
      "caltrops",
      "fan_of_knives",
    ],
  },
  CLERIC: {
    hp: 220,
    mana: 120,
    str: 20,
    agi: 10,
    int: 16,
    speedTilesPerSecond: 6,
    attackRange: 1,
    attackCooldownMs: 500,
    attackWindupMs: 140,
    armor: 8,
    maxCompanions: 1,
    // Q: holy_strike (dmg) | W: heal (self heal) | E: divine_shield (invuln) | R: holy_nova (AoE heal) | T: curse (debuff) | Y: smite (ranged dmg)
    abilities: ["holy_strike", "heal", "divine_shield", "holy_nova", "curse", "smite"],
  },
  PALADIN: {
    hp: 230,
    mana: 100,
    str: 22,
    agi: 10,
    int: 14,
    speedTilesPerSecond: 6,
    attackRange: 1,
    attackCooldownMs: 480,
    attackWindupMs: 130,
    armor: 12,
    maxCompanions: 2,
    // Q: judgment (holy melee) | W: lay_on_hands (self heal) | E: consecration (AoE holy) | R: aura_of_protection (armor buff) | T: holy_bolt (ranged dmg)
    abilities: ["judgment", "lay_on_hands", "consecration", "aura_of_protection", "holy_bolt"],
  },
  NECROMANCER: {
    hp: 120,
    mana: 200,
    str: 4,
    agi: 8,
    int: 32,
    speedTilesPerSecond: 7,
    attackRange: 5,
    attackCooldownMs: 700,
    attackWindupMs: 150,
    armor: 1,
    maxCompanions: 3,
    // Q: shadow_bolt (dmg) | W: soul_drain (leech) | E: curse (debuff) | R: banshee_wail (AoE debuff) | T: hemorrhage (leech) | Y: summon_skeleton
    abilities: [
      "shadow_bolt",
      "soul_drain",
      "curse",
      "banshee_wail",
      "hemorrhage",
      "summon_skeleton",
      "summon_zombie",
      "soul_blast",
    ],
  },
  DRUID: {
    hp: 180,
    mana: 140,
    str: 10,
    agi: 16,
    int: 18,
    speedTilesPerSecond: 7,
    attackRange: 4,
    attackCooldownMs: 550,
    attackWindupMs: 120,
    armor: 6,
    maxCompanions: 3,
    // Q: poison_arrow (DoT) | W: heal (self heal) | E: entangling_roots (stun) | R: acid_splash (AoE DoT) | T: cleansing_rain (AoE heal) | Y: thunderstorm (AoE)
    abilities: [
      "poison_arrow",
      "heal",
      "entangling_roots",
      "acid_splash",
      "cleansing_rain",
      "thunderstorm",
      "bear_form",
      "cat_form",
      "tree_form",
    ],
  },
};

export const LEVEL_UP_STATS: Record<
  string,
  { str: number; agi: number; int: number; hp: number; mana: number }
> = {
  WARRIOR: { str: 3, agi: 1, int: 0, hp: 30, mana: 5 },
  MAGE: { str: 0, agi: 1, int: 3, hp: 18, mana: 20 },
  RANGER: { str: 1, agi: 3, int: 0, hp: 22, mana: 10 },
  ROGUE: { str: 1, agi: 3, int: 0, hp: 22, mana: 8 },
  CLERIC: { str: 1, agi: 0, int: 3, hp: 26, mana: 15 },
  PALADIN: { str: 2, agi: 0, int: 2, hp: 28, mana: 12 },
  NECROMANCER: { str: 0, agi: 1, int: 4, hp: 15, mana: 25 },
  DRUID: { str: 1, agi: 1, int: 2, hp: 24, mana: 14 },
};

export const EXP_TABLE = [
  0, 100, 250, 450, 700, 1000, 1350, 1750, 2200, 2700, 3250, 3850, 4500, 5200, 5950, 6750, 7600,
  8500, 9450, 10450,
];
