import type { BarkTrigger, NpcStats, NpcType } from "../types";

export const NPC_APPEARANCE: Record<string, { bodyId: number; headId: number }> = {
  orc: { bodyId: 30, headId: 0 },
  skeleton: { bodyId: 35, headId: 0 },
  goblin: { bodyId: 45, headId: 0 },
  wolf: { bodyId: 65, headId: 0 },
  merchant: { bodyId: 5, headId: 0 },
  spider: { bodyId: 10, headId: 0 },
  ghost: { bodyId: 15, headId: 0 },
  lich: { bodyId: 70, headId: 0 },
  banker: { bodyId: 5, headId: 0 },
  zombie: { bodyId: 40, headId: 0 },
  troll: { bodyId: 25, headId: 0 },
  bat: { bodyId: 50, headId: 0 },
  dark_knight: { bodyId: 3, headId: 0 },
  horse: { bodyId: 65, headId: 0 },
  skeleton_archer: { bodyId: 35, headId: 0 },
  vampire: { bodyId: 70, headId: 0 },
  gargoyle: { bodyId: 50, headId: 0 },
  elephant: { bodyId: 80, headId: 0 },
  dragon: { bodyId: 85, headId: 0 },
  bear: { bodyId: 75, headId: 0 },
  mana_spring: { bodyId: 1, headId: 0 },
  explosive_trap: { bodyId: 3, headId: 0 },
  phantom_pet: { bodyId: 65, headId: 0 },
  decoy: { bodyId: 45, headId: 0 },
};

const _NPC_STATS: Partial<Record<string, Partial<NpcStats>>> = {
  orc: {
    hp: 120,
    str: 12,
    agi: 10,
    int: 5,
    speedTilesPerSecond: 3.5,
    attackRange: 1,
    attackCooldownMs: 800,
    attackWindupMs: 200,
    armor: 15,
    // Berserker self-buff when health is low
    abilities: ["enrage"],
    expReward: 80,
    // Uses enrage tactically rather than on every opportunity
    abilityCastChance: 0.6,
    minLevel: 10,
    maxLevel: 25,
    aggroRange: 5,
    barks: {
      aggro: ["RAAAAGH!", "You dare come here?!", "CRUSH!"],
      low_hp: ["You'll pay for this!", "ARGH!", "Not done yet!"],
      kill: ["ORC STRONG!", "Next!", "Too easy."],
    },
  },
  skeleton: {
    hp: 60,
    str: 8,
    agi: 15,
    int: 10,
    speedTilesPerSecond: 4,
    // Ranged mage unit — stays at mid-range and kites; attackRange > 1 also
    // makes auto-attacks use the AGI-scaling ranged formula.
    attackRange: 6,
    attackCooldownMs: 600,
    attackWindupMs: 150,
    armor: 10,
    abilities: ["shadow_bolt"],
    expReward: 45,
    abilityCastChance: 0.55,
    minLevel: 5,
    maxLevel: 15,
    aggroRange: 5,
    barks: {
      aggro: ["*rattles*", "Join us...", "The dead hunger!"],
      low_hp: ["*creaks*", "Crumbling..."],
    },
  },
  goblin: {
    hp: 40,
    str: 6,
    agi: 18,
    int: 5,
    speedTilesPerSecond: 4.5,
    attackRange: 1,
    attackCooldownMs: 700,
    attackWindupMs: 120,
    armor: 5,
    // Throws a small fire splash around itself
    abilities: ["fire_breath"],
    expReward: 30,
    fleesWhenLow: true,
    // Fire breath is a situational trick — rely mostly on quick melee
    abilityCastChance: 0.3,
    minLevel: 1,
    maxLevel: 10,
    aggroRange: 3,
    barks: {
      aggro: ["Hehehe!", "Kill kill kill!", "Goblins ATTACK!"],
      low_hp: ["Retreat!", "Help meee!", "Too strong!"],
      idle: ["Mine mine mine...", "Shiny things..."],
    },
  },
  wolf: {
    hp: 80,
    str: 10,
    agi: 20,
    int: 5,
    speedTilesPerSecond: 5.5,
    attackRange: 1,
    attackCooldownMs: 600,
    attackWindupMs: 120,
    armor: 8,
    abilities: [],
    expReward: 55,
    fleesWhenLow: true,
    minLevel: 1,
    maxLevel: 10,
    aggroRange: 6,
    barks: {
      aggro: ["*GROWL*", "*HOWL*", "*SNARL*"],
      low_hp: ["*whimper*", "*yelp*"],
    },
  },
  merchant: {
    hp: 1000,
    str: 10,
    agi: 10,
    int: 10,
    speedTilesPerSecond: 0,
    attackRange: 0,
    attackCooldownMs: 0,
    attackWindupMs: 0,
    armor: 100,
    abilities: [],
    passive: true,
    barks: {
      idle: ["Welcome, adventurer!", "Fine wares, fine prices!", "Step right up!"],
    },
  },
  spider: {
    hp: 50,
    str: 7,
    agi: 25,
    int: 5,
    speedTilesPerSecond: 5.5,
    attackRange: 1,
    attackCooldownMs: 700,
    attackWindupMs: 100,
    armor: 2,
    // Poison bite (DoT) + web shot (stun)
    abilities: ["poison_bite", "web_shot"],
    expReward: 35,
    fleesWhenLow: true,
    // Abilities are occasional — relies mostly on quick auto-attacks
    abilityCastChance: 0.4,
    minLevel: 5,
    maxLevel: 15,
    aggroRange: 4,
    barks: {
      aggro: ["*hiss*", "*skitter*"],
    },
  },
  ghost: {
    hp: 70,
    str: 5,
    agi: 10,
    int: 20,
    speedTilesPerSecond: 3,
    attackRange: 1,
    attackCooldownMs: 1000,
    attackWindupMs: 200,
    armor: 0,
    // Life drain (leech) + wail to weaken nearby enemies
    abilities: ["soul_drain", "banshee_wail"],
    expReward: 70,
    // Heavily ability-focused fighter
    abilityCastChance: 0.55,
    minLevel: 10,
    maxLevel: 25,
    aggroRange: 5,
    barks: {
      aggro: ["*wailing*", "You cannot escape death...", "Join the void..."],
      low_hp: ["Not yet!", "*screech*"],
    },
  },
  lich: {
    hp: 500,
    str: 10,
    agi: 10,
    int: 40,
    speedTilesPerSecond: 1.5,
    // Ranged boss — stays at distance and fires long-range shadow bolts.
    // High attackRange also enables the kiting back-away behaviour.
    attackRange: 8,
    attackCooldownMs: 1500,
    attackWindupMs: 500,
    armor: 25,
    // Full boss toolkit: ranged nuke, frost slow, AoE debuff, summons
    abilities: ["shadow_bolt", "frost_breath", "banshee_wail", "summon_skeleton"],
    expReward: 500,
    // Boss aggressively rotates its full ability kit
    abilityCastChance: 0.7,
    // Bosses should not appear in random spawns — place via map.npcs only
    rareSpawn: true,
    // Summon ability creates skeleton minions
    summonType: "skeleton",
    minLevel: 30,
    aggroRange: 8,
    barks: {
      aggro: [
        "Foolish mortal! Your bones will serve me!",
        "I have waited centuries for prey...",
        "Embrace oblivion!",
      ],
      low_hp: [
        "Impossible! My power is limitless!",
        "RISE, my minions! RISE!",
        "You cannot kill what is already dead!",
      ],
      kill: ["Your soul is mine now.", "Another servant for eternity.", "Pathetic."],
    },
    // Boss phase mechanics
    bossPhaseThreshold: 0.5,
    phaseAbilities: ["banshee_wail", "summon_skeleton"],
    rareSpawnIntervalMs: 300_000, // 5 minutes
  },
  zombie: {
    hp: 90,
    str: 10,
    agi: 4,
    int: 8,
    speedTilesPerSecond: 2.5,
    attackRange: 1,
    attackCooldownMs: 1200,
    attackWindupMs: 300,
    armor: 8,
    // Bites to apply a slow-ticking, long-lasting disease DoT
    abilities: ["disease_bite"],
    expReward: 60,
    abilityCastChance: 0.5,
    minLevel: 5,
    maxLevel: 15,
    aggroRange: 4,
    barks: {
      aggro: ["*groan*", "*moan*", "...braaiins..."],
      low_hp: ["*gurgle*"],
    },
  },
  troll: {
    hp: 250,
    str: 22,
    agi: 6,
    int: 5,
    speedTilesPerSecond: 2,
    attackRange: 1,
    attackCooldownMs: 1000,
    attackWindupMs: 350,
    armor: 20,
    // Uses an emergency self-heal when critically low on HP
    abilities: ["troll_regen"],
    expReward: 150,
    // High chance so it reliably heals itself when desperate
    abilityCastChance: 0.7,
    minLevel: 20,
    maxLevel: 40,
    aggroRange: 5,
    barks: {
      aggro: ["TROLL SMASH!", "You small, me hungry.", "CRUSH!"],
      low_hp: ["TROLL HEAL!", "You no win!", "GRAAAH!"],
    },
  },
  bat: {
    hp: 30,
    str: 4,
    agi: 28,
    int: 12,
    speedTilesPerSecond: 5.5,
    attackRange: 1,
    attackCooldownMs: 500,
    attackWindupMs: 80,
    armor: 2,
    // Vampire bat drains life force from its victim
    abilities: ["soul_drain"],
    expReward: 25,
    fleesWhenLow: true,
    abilityCastChance: 0.4,
    minLevel: 1,
    maxLevel: 10,
    aggroRange: 3,
    barks: {
      aggro: ["*SCREECH*", "*flap flap*"],
    },
  },
  dark_knight: {
    hp: 350,
    str: 28,
    agi: 15,
    int: 12,
    speedTilesPerSecond: 3,
    // Melee fighter — closes to adjacent range for both auto-attacks and
    // point-blank shadow bolt bursts; enrage activates a STR berserker window.
    attackRange: 1,
    attackCooldownMs: 900,
    attackWindupMs: 250,
    armor: 30,
    abilities: ["enrage", "shadow_bolt"],
    expReward: 400,
    abilityCastChance: 0.65,
    // Elite — place via map.npcs; should not appear in random spawns
    rareSpawn: true,
    minLevel: 20,
    maxLevel: 40,
    aggroRange: 7,
    barks: {
      aggro: [
        "For the Dark Lord!",
        "Your light ends here.",
        "None shall pass!",
      ],
      low_hp: ["My armour holds!", "This is not over!", "ENRAGE!"],
      kill: ["Another falls.", "Kneel before darkness."],
    },
    bossPhaseThreshold: 0.4,
    phaseAbilities: ["shadow_bolt"],
    rareSpawnIntervalMs: 180_000, // 3 minutes
  },
  banker: {
    hp: 100,
    str: 5,
    agi: 5,
    int: 5,
    speedTilesPerSecond: 0,
    attackRange: 1,
    attackCooldownMs: 1000,
    attackWindupMs: 200,
    armor: 100,
    abilities: [],
    passive: true,
    barks: {
      idle: ["Your gold is safe with us.", "Deposits and withdrawals here!", "Banking hours: always."],
    },
  },
  horse: {
    hp: 150,
    str: 5,
    agi: 30,
    int: 3,
    speedTilesPerSecond: 5.5,
    attackRange: 0,
    attackCooldownMs: 0,
    attackWindupMs: 0,
    armor: 5,
    abilities: [],
    expReward: 0,
    passive: true,
    fleesWhenLow: true,
  },
  skeleton_archer: {
    hp: 80,
    str: 10,
    agi: 20,
    int: 5,
    speedTilesPerSecond: 3.5,
    attackRange: 6,
    attackCooldownMs: 800,
    attackWindupMs: 200,
    armor: 12,
    abilities: [],
    expReward: 65,
    minLevel: 10,
    maxLevel: 25,
    aggroRange: 6,
    barks: {
      aggro: ["*twang*", "Target acquired.", "*rattles*"],
    },
  },
  vampire: {
    hp: 200,
    str: 20,
    agi: 25,
    int: 20,
    speedTilesPerSecond: 4,
    attackRange: 1,
    attackCooldownMs: 700,
    attackWindupMs: 150,
    armor: 25,
    abilities: ["soul_drain"],
    expReward: 180,
    abilityCastChance: 0.6,
    minLevel: 20,
    maxLevel: 35,
    aggroRange: 6,
    barks: {
      aggro: ["I hunger...", "Your blood calls to me.", "Come, let me taste you."],
      low_hp: ["Impossible... I cannot die!", "This wounds me deeply."],
    },
  },
  gargoyle: {
    hp: 300,
    str: 25,
    agi: 10,
    int: 5,
    speedTilesPerSecond: 2,
    attackRange: 1,
    attackCooldownMs: 1200,
    attackWindupMs: 300,
    armor: 40,
    abilities: [],
    expReward: 220,
    abilityCastChance: 0.3,
    minLevel: 20,
    maxLevel: 35,
    aggroRange: 5,
    barks: {
      aggro: ["*stone grinding*", "BEGONE!", "*ROAR*"],
    },
  },
  elephant: {
    hp: 400,
    str: 25,
    agi: 5,
    int: 5,
    speedTilesPerSecond: 2.5,
    attackRange: 1,
    attackCooldownMs: 1500,
    attackWindupMs: 400,
    armor: 30,
    abilities: [],
    expReward: 120,
    abilityCastChance: 0,
    minLevel: 15,
    maxLevel: 25,
    aggroRange: 5,
    barks: {
      aggro: ["*TRUMPET*", "*STOMP*"],
    },
  },
  dragon: {
    hp: 800,
    str: 35,
    agi: 20,
    int: 30,
    speedTilesPerSecond: 6,
    attackRange: 4,
    attackCooldownMs: 1200,
    attackWindupMs: 300,
    armor: 40,
    abilities: ["fire_breath", "frost_breath"],
    expReward: 300,
    abilityCastChance: 0.6,
    minLevel: 40,
    maxLevel: 50,
    aggroRange: 8,
    rareSpawn: true,
    barks: {
      aggro: [
        "You dare challenge a DRAGON?!",
        "Insolent creature... BURN!",
        "*ROOOAAAAR*",
      ],
      low_hp: [
        "You are stronger than I expected, insect.",
        "Feel my TRUE power!",
        "*ENRAGED ROAR*",
      ],
      kill: ["Pathetic insects.", "My hoard is safe.", "WYRM TRIUMPHANT!"],
    },
    bossPhaseThreshold: 0.5,
    phaseAbilities: ["frost_breath"],
    rareSpawnIntervalMs: 600_000, // 10 minutes
  },
  bear: {
    hp: 200,
    str: 18,
    agi: 8,
    int: 5,
    speedTilesPerSecond: 3.5,
    attackRange: 1,
    attackCooldownMs: 1000,
    attackWindupMs: 250,
    armor: 15,
    abilities: [],
    expReward: 60,
    abilityCastChance: 0,
    minLevel: 8,
    maxLevel: 15,
    aggroRange: 5,
    barks: {
      aggro: ["*GROWL*", "*ROAR*"],
    },
  },
  mana_spring: {
    hp: 100,
    speedTilesPerSecond: 0,
    passive: true,
    armor: 5,
    abilities: [],
    expReward: 0,
  },
  explosive_trap: {
    hp: 10,
    speedTilesPerSecond: 0,
    passive: true,
    armor: 0,
    abilities: [],
    expReward: 0,
  },
  phantom_pet: {
    hp: 100,
    speedTilesPerSecond: 6,
    attackRange: 1,
    attackCooldownMs: 800,
    armor: 10,
    abilities: [],
    expReward: 0,
  },
  decoy: {
    hp: 200,
    speedTilesPerSecond: 0,
    passive: true,
    armor: 20,
    abilities: [],
    expReward: 0,
  },
};


export const NPC_STATS: Record<NpcType, NpcStats> = Object.fromEntries(
  Object.entries(_NPC_STATS).map(([k, v]) => {
    const stats: NpcStats = {
      passive: false,
      fleesWhenLow: false,
      abilityCastChance: 0.4,
      rareSpawn: false,
      ...v,
    } as NpcStats;
    return [k, stats];
  }),
) as Record<NpcType, NpcStats>;

export const NPC_TYPES: NpcType[] = Object.keys(_NPC_STATS) as NpcType[];

export interface DropTableEntry {
  itemId: string;
  chance: number;
  min: number;
  max: number;
}

export const NPC_DROPS: Record<string, DropTableEntry[]> = {
  orc: [
    { itemId: "great_health_potion", chance: 0.1, min: 1, max: 2 },
    { itemId: "great_mana_potion", chance: 0.1, min: 1, max: 2 },
    { itemId: "iron_sword", chance: 0.08, min: 1, max: 1 },
    { itemId: "steel_sword", chance: 0.01, min: 1, max: 1 },
    { itemId: "chainmail", chance: 0.03, min: 1, max: 1 },
    { itemId: "iron_helmet", chance: 0.05, min: 1, max: 1 },
    { itemId: "wooden_shield", chance: 0.05, min: 1, max: 1 },
    { itemId: "gold", chance: 0.6, min: 15, max: 40 },
  ],
  skeleton: [
    { itemId: "health_potion", chance: 0.2, min: 1, max: 2 },
    { itemId: "bronze_axe", chance: 0.05, min: 1, max: 1 },
    { itemId: "iron_shield", chance: 0.04, min: 1, max: 1 },
    { itemId: "ring_of_strength", chance: 0.02, min: 1, max: 1 },
    { itemId: "gold", chance: 0.4, min: 8, max: 20 },
  ],
  goblin: [
    { itemId: "health_potion", chance: 0.2, min: 1, max: 1 },
    { itemId: "mana_potion", chance: 0.1, min: 1, max: 1 },
    { itemId: "iron_dagger", chance: 0.06, min: 1, max: 1 },
    { itemId: "leather_armor", chance: 0.04, min: 1, max: 1 },
    { itemId: "ring_of_agility", chance: 0.01, min: 1, max: 1 },
    { itemId: "gold", chance: 0.5, min: 5, max: 15 },
  ],
  wolf: [
    { itemId: "health_potion", chance: 0.05, min: 1, max: 1 },
    { itemId: "gold", chance: 0.4, min: 5, max: 15 },
  ],
  spider: [
    { itemId: "mana_potion", chance: 0.1, min: 1, max: 1 },
    { itemId: "gold", chance: 0.3, min: 10, max: 25 },
  ],
  ghost: [
    { itemId: "ring_of_intellect", chance: 0.05, min: 1, max: 1 },
    { itemId: "mana_potion", chance: 0.15, min: 1, max: 2 },
    { itemId: "gold", chance: 0.2, min: 20, max: 50 },
  ],
  lich: [
    { itemId: "steel_sword", chance: 0.5, min: 1, max: 1 },
    { itemId: "chainmail", chance: 0.4, min: 1, max: 1 },
    { itemId: "ring_of_intellect", chance: 0.2, min: 1, max: 1 },
    { itemId: "health_potion", chance: 1.0, min: 5, max: 10 },
    { itemId: "mana_potion", chance: 1.0, min: 5, max: 10 },
    { itemId: "gold", chance: 1.0, min: 500, max: 1500 },
  ],
  zombie: [
    { itemId: "health_potion", chance: 0.15, min: 1, max: 1 },
    { itemId: "leather_armor", chance: 0.05, min: 1, max: 1 },
    { itemId: "ring_of_vitality", chance: 0.02, min: 1, max: 1 },
    { itemId: "gold", chance: 0.45, min: 8, max: 20 },
  ],
  troll: [
    { itemId: "great_health_potion", chance: 0.2, min: 1, max: 2 },
    { itemId: "iron_sword", chance: 0.1, min: 1, max: 1 },
    { itemId: "iron_helmet", chance: 0.08, min: 1, max: 1 },
    { itemId: "ring_of_strength", chance: 0.05, min: 1, max: 1 },
    { itemId: "gold", chance: 0.7, min: 30, max: 80 },
  ],
  bat: [
    { itemId: "mana_potion", chance: 0.12, min: 1, max: 1 },
    { itemId: "gold", chance: 0.3, min: 3, max: 12 },
  ],
  dark_knight: [
    { itemId: "steel_sword", chance: 0.15, min: 1, max: 1 },
    { itemId: "chainmail", chance: 0.12, min: 1, max: 1 },
    { itemId: "plate_armor", chance: 0.04, min: 1, max: 1 },
    { itemId: "great_health_potion", chance: 0.3, min: 1, max: 3 },
    { itemId: "ring_of_strength", chance: 0.06, min: 1, max: 1 },
    { itemId: "gold", chance: 0.8, min: 80, max: 200 },
  ],
  // Passive NPCs — no drops, but entry prevents undefined lookups
  merchant: [],
  banker: [],
  // Horse is a mount — no combat drops
  horse: [],
  skeleton_archer: [
    { itemId: "health_potion", chance: 0.2, min: 1, max: 2 },
    { itemId: "hunting_bow", chance: 0.05, min: 1, max: 1 },
    { itemId: "bone_sword", chance: 0.03, min: 1, max: 1 },
    { itemId: "gold", chance: 0.5, min: 15, max: 30 },
  ],
  vampire: [
    { itemId: "great_health_potion", chance: 0.2, min: 1, max: 3 },
    { itemId: "vampire_cape", chance: 0.05, min: 1, max: 1 },
    { itemId: "blood_amulet", chance: 0.03, min: 1, max: 1 },
    { itemId: "gold", chance: 0.8, min: 50, max: 120 },
  ],
  gargoyle: [
    { itemId: "great_health_potion", chance: 0.2, min: 1, max: 2 },
    { itemId: "plate_armor", chance: 0.02, min: 1, max: 1 },
    { itemId: "bone_sword", chance: 0.05, min: 1, max: 1 },
    { itemId: "gold", chance: 0.7, min: 40, max: 100 },
  ],
};

/**
 * Returns the drop table for an NPC type.
 * Always returns an array (empty for passive/mount NPCs).
 */
export function buildDropRolls(type: NpcType): DropTableEntry[] {
  return NPC_DROPS[type] ?? [];
}
