import type { ClassStats, SpellDef } from "./types";

export const CLASS_APPEARANCE: Record<string, { bodyId: number; headId: number }> = {
  warrior:  { bodyId: 40, headId: 1 },
  wizard:   { bodyId: 22, headId: 3 },
  archer:   { bodyId: 60, headId: 2 },
  assassin: { bodyId: 45, headId: 4 },
  paladin:  { bodyId: 50, headId: 5 },
  druid:    { bodyId: 55, headId: 6 },
};

export const NPC_APPEARANCE: Record<string, { bodyId: number; headId: number }> = {
  orc:      { bodyId: 30, headId: 0 }, // Using 0 for headId if body includes head or just to separate
  skeleton: { bodyId: 35, headId: 0 },
  goblin:   { bodyId: 45, headId: 0 }, // Reusing assassin body for now if no specific goblin
  wolf:     { bodyId: 65, headId: 0 },
};

export const TICK_RATE = 20;
export const TICK_MS = 1000 / TICK_RATE;
export const TILE_SIZE = 32;
export const GCD_MS = 120;
export const BUFFER_WINDOW_MS = 200;
export const PATCH_RATE = 20;

export const CLASS_STATS: Record<string, ClassStats> = {
  warrior: {
    hp: 180,
    mana: 40,
    str: 25,
    agi: 12,
    int: 6,
    speedTilesPerSecond: 7,
    meleeRange: 1,
    meleeCooldownMs: 450,
    meleeWindupMs: 120,
    spells: ["war_cry", "shield_bash"],
  },
  wizard: {
    hp: 80,
    mana: 150,
    str: 6,
    agi: 10,
    int: 28,
    speedTilesPerSecond: 7,
    meleeRange: 1,
    meleeCooldownMs: 650,
    meleeWindupMs: 120,
    spells: ["fireball", "ice_bolt", "thunderstorm", "mana_shield"],
  },
  archer: {
    hp: 100,
    mana: 80,
    str: 10,
    agi: 26,
    int: 10,
    speedTilesPerSecond: 7,
    meleeRange: 5,
    meleeCooldownMs: 500,
    meleeWindupMs: 100,
    spells: ["multi_shot", "poison_arrow", "evasion"],
  },
  assassin: {
    hp: 95,
    mana: 60,
    str: 14,
    agi: 24,
    int: 8,
    speedTilesPerSecond: 8,
    meleeRange: 1,
    meleeCooldownMs: 350,
    meleeWindupMs: 80,
    spells: ["backstab", "stealth", "envenom"],
  },
  paladin: {
    hp: 160,
    mana: 100,
    str: 20,
    agi: 10,
    int: 16,
    speedTilesPerSecond: 6,
    meleeRange: 1,
    meleeCooldownMs: 500,
    meleeWindupMs: 140,
    spells: ["holy_strike", "heal", "divine_shield"],
  },
  druid: {
    hp: 110,
    mana: 130,
    str: 10,
    agi: 14,
    int: 24,
    speedTilesPerSecond: 7,
    meleeRange: 1,
    meleeCooldownMs: 550,
    meleeWindupMs: 120,
    spells: ["entangle", "rejuvenation", "lightning_bolt", "shapeshift"],
  },
};

export const NPC_STATS: Record<string, ClassStats> = {
  orc: {
    hp: 120,
    mana: 0,
    str: 18,
    agi: 10,
    int: 5,
    speedTilesPerSecond: 5,
    meleeRange: 1,
    meleeCooldownMs: 800,
    meleeWindupMs: 200,
    spells: [],
  },
  skeleton: {
    hp: 60,
    mana: 0,
    str: 12,
    agi: 15,
    int: 5,
    speedTilesPerSecond: 6,
    meleeRange: 1,
    meleeCooldownMs: 600,
    meleeWindupMs: 150,
    spells: [],
  },
  goblin: {
    hp: 40,
    mana: 0,
    str: 8,
    agi: 18,
    int: 5,
    speedTilesPerSecond: 7,
    meleeRange: 1,
    meleeCooldownMs: 500,
    meleeWindupMs: 100,
    spells: [],
  },
  wolf: {
    hp: 80,
    mana: 0,
    str: 15,
    agi: 20,
    int: 5,
    speedTilesPerSecond: 8,
    meleeRange: 1,
    meleeCooldownMs: 600,
    meleeWindupMs: 120,
    spells: [],
  },
};

export const SPELLS: Record<string, SpellDef> = {
  // ── Warrior ──
  war_cry: {
    id: "war_cry",
    rangeTiles: 0,
    manaCost: 15,
    baseDamage: 0,
    scalingStat: "str",
    scalingRatio: 0,
    cooldownMs: 12000,
    windupMs: 100,
    effect: "buff",
    key: "Q",
    durationMs: 8000,
    buffStat: "str",
    buffAmount: 10,
  },
  shield_bash: {
    id: "shield_bash",
    rangeTiles: 1,
    manaCost: 20,
    baseDamage: 15,
    scalingStat: "str",
    scalingRatio: 0.6,
    cooldownMs: 6000,
    windupMs: 140,
    effect: "stun",
    key: "W",
    durationMs: 2000,
  },

  // ── Wizard ──
  fireball: {
    id: "fireball",
    rangeTiles: 6,
    manaCost: 25,
    baseDamage: 30,
    scalingStat: "int",
    scalingRatio: 0.8,
    cooldownMs: 450,
    windupMs: 140,
    effect: "damage",
    key: "Q",
  },
  ice_bolt: {
    id: "ice_bolt",
    rangeTiles: 5,
    manaCost: 20,
    baseDamage: 20,
    scalingStat: "int",
    scalingRatio: 0.6,
    cooldownMs: 600,
    windupMs: 120,
    effect: "damage",
    key: "W",
  },
  thunderstorm: {
    id: "thunderstorm",
    rangeTiles: 5,
    manaCost: 45,
    baseDamage: 25,
    scalingStat: "int",
    scalingRatio: 0.7,
    cooldownMs: 3000,
    windupMs: 200,
    effect: "aoe",
    key: "E",
    aoeRadius: 2,
  },
  mana_shield: {
    id: "mana_shield",
    rangeTiles: 0,
    manaCost: 30,
    baseDamage: 0,
    scalingStat: "int",
    scalingRatio: 0,
    cooldownMs: 15000,
    windupMs: 80,
    effect: "buff",
    key: "R",
    durationMs: 6000,
    buffStat: "armor",
    buffAmount: 15,
  },

  // ── Archer ──
  multi_shot: {
    id: "multi_shot",
    rangeTiles: 5,
    manaCost: 25,
    baseDamage: 18,
    scalingStat: "agi",
    scalingRatio: 0.5,
    cooldownMs: 2000,
    windupMs: 120,
    effect: "aoe",
    key: "Q",
    aoeRadius: 2,
  },
  poison_arrow: {
    id: "poison_arrow",
    rangeTiles: 6,
    manaCost: 20,
    baseDamage: 10,
    scalingStat: "agi",
    scalingRatio: 0.4,
    cooldownMs: 4000,
    windupMs: 100,
    effect: "dot",
    key: "W",
    dotDamage: 5,
    dotIntervalMs: 1000,
    dotDurationMs: 5000,
  },
  evasion: {
    id: "evasion",
    rangeTiles: 0,
    manaCost: 20,
    baseDamage: 0,
    scalingStat: "agi",
    scalingRatio: 0,
    cooldownMs: 10000,
    windupMs: 60,
    effect: "buff",
    key: "E",
    durationMs: 5000,
    buffStat: "agi",
    buffAmount: 15,
  },

  // ── Assassin ──
  backstab: {
    id: "backstab",
    rangeTiles: 1,
    manaCost: 25,
    baseDamage: 40,
    scalingStat: "agi",
    scalingRatio: 1.0,
    cooldownMs: 3000,
    windupMs: 80,
    effect: "damage",
    key: "Q",
  },
  stealth: {
    id: "stealth",
    rangeTiles: 0,
    manaCost: 30,
    baseDamage: 0,
    scalingStat: "agi",
    scalingRatio: 0,
    cooldownMs: 15000,
    windupMs: 60,
    effect: "stealth",
    key: "W",
    durationMs: 6000,
  },
  envenom: {
    id: "envenom",
    rangeTiles: 1,
    manaCost: 20,
    baseDamage: 8,
    scalingStat: "agi",
    scalingRatio: 0.3,
    cooldownMs: 5000,
    windupMs: 80,
    effect: "dot",
    key: "E",
    dotDamage: 6,
    dotIntervalMs: 1000,
    dotDurationMs: 6000,
  },

  // ── Paladin ──
  holy_strike: {
    id: "holy_strike",
    rangeTiles: 1,
    manaCost: 20,
    baseDamage: 25,
    scalingStat: "str",
    scalingRatio: 0.7,
    cooldownMs: 2000,
    windupMs: 140,
    effect: "damage",
    key: "Q",
  },
  heal: {
    id: "heal",
    rangeTiles: 0,
    manaCost: 30,
    baseDamage: 40,
    scalingStat: "int",
    scalingRatio: 0.8,
    cooldownMs: 4000,
    windupMs: 160,
    effect: "heal",
    key: "W",
  },
  divine_shield: {
    id: "divine_shield",
    rangeTiles: 0,
    manaCost: 40,
    baseDamage: 0,
    scalingStat: "int",
    scalingRatio: 0,
    cooldownMs: 20000,
    windupMs: 100,
    effect: "buff",
    key: "E",
    durationMs: 4000,
    buffStat: "invulnerable",
    buffAmount: 1,
  },

  // ── Druid ──
  entangle: {
    id: "entangle",
    rangeTiles: 4,
    manaCost: 25,
    baseDamage: 10,
    scalingStat: "int",
    scalingRatio: 0.3,
    cooldownMs: 6000,
    windupMs: 140,
    effect: "stun",
    key: "Q",
    durationMs: 2500,
  },
  rejuvenation: {
    id: "rejuvenation",
    rangeTiles: 0,
    manaCost: 25,
    baseDamage: 8,
    scalingStat: "int",
    scalingRatio: 0.5,
    cooldownMs: 5000,
    windupMs: 100,
    effect: "heal",
    key: "W",
    durationMs: 6000,
  },
  lightning_bolt: {
    id: "lightning_bolt",
    rangeTiles: 5,
    manaCost: 30,
    baseDamage: 28,
    scalingStat: "int",
    scalingRatio: 0.75,
    cooldownMs: 1500,
    windupMs: 120,
    effect: "damage",
    key: "E",
  },
  shapeshift: {
    id: "shapeshift",
    rangeTiles: 0,
    manaCost: 35,
    baseDamage: 0,
    scalingStat: "int",
    scalingRatio: 0,
    cooldownMs: 18000,
    windupMs: 120,
    effect: "buff",
    key: "R",
    durationMs: 10000,
    buffStat: "str",
    buffAmount: 12,
  },
};
