import { type ClassType, EquipmentSlot } from "./types";

export type ItemSlot = "weapon" | "armor" | "shield" | "helmet" | "ring" | "mount" | "consumable";
export type ItemRarity = "common" | "uncommon" | "rare";

export type Item = {
  id: string;
  name: string;
  slot: ItemSlot;
  rarity: ItemRarity;
  stats: {
    str?: number;
    agi?: number;
    int?: number;
    hp?: number;
    mana?: number;
    armor?: number;
    /** Extra movement speed in tiles/s when this mount is equipped. */
    speedBonus?: number;
  };
  goldValue: number;
  requiredClass?: ClassType[];
  consumeEffect?: {
    healHp?: number;
    healMana?: number;
  };
  stackable?: boolean;
  aoWeaponId?: number;
  aoShieldId?: number;
  aoHelmetId?: number;
  /** NPC type string this item represents when used as a mount. */
  mountNpcType?: string;
};

export const ITEMS: Record<string, Item> = {
  // --- WEAPONS ---
  club: {
    id: "club",
    name: "items.club.name",
    slot: "weapon",
    rarity: "common",
    stats: { str: 2 },
    goldValue: 5,
    aoWeaponId: 1,
  },
  dagger: {
    id: "dagger",
    name: "items.dagger.name",
    slot: "weapon",
    rarity: "common",
    stats: { agi: 2 },
    goldValue: 8,
    aoWeaponId: 2,
  },
  iron_sword: {
    id: "iron_sword",
    name: "items.iron_sword.name",
    slot: "weapon",
    rarity: "common",
    stats: { str: 5 },
    goldValue: 20,
    requiredClass: ["WARRIOR", "CLERIC", "PALADIN"],
    aoWeaponId: 14,
  },
  steel_sword: {
    id: "steel_sword",
    name: "items.steel_sword.name",
    slot: "weapon",
    rarity: "uncommon",
    stats: { str: 10 },
    goldValue: 60,
    requiredClass: ["WARRIOR", "CLERIC", "PALADIN"],
    aoWeaponId: 21,
  },
  flame_blade: {
    id: "flame_blade",
    name: "items.flame_blade.name",
    slot: "weapon",
    rarity: "rare",
    stats: { str: 18, int: 5 },
    goldValue: 250,
    requiredClass: ["WARRIOR"],
    aoWeaponId: 30,
  },
  magic_staff: {
    id: "magic_staff",
    name: "items.magic_staff.name",
    slot: "weapon",
    rarity: "common",
    stats: { int: 6 },
    goldValue: 25,
    requiredClass: ["MAGE"],
    aoWeaponId: 6,
  },
  arcane_staff: {
    id: "arcane_staff",
    name: "items.arcane_staff.name",
    slot: "weapon",
    rarity: "uncommon",
    stats: { int: 12, mana: 20 },
    goldValue: 80,
    requiredClass: ["MAGE"],
    aoWeaponId: 18,
  },
  staff_of_storms: {
    id: "staff_of_storms",
    name: "items.staff_of_storms.name",
    slot: "weapon",
    rarity: "rare",
    stats: { int: 22, mana: 50 },
    goldValue: 300,
    requiredClass: ["MAGE"],
    aoWeaponId: 34,
  },
  short_bow: {
    id: "short_bow",
    name: "items.short_bow.name",
    slot: "weapon",
    rarity: "common",
    stats: { agi: 4 },
    goldValue: 12,
    requiredClass: ["RANGER"],
    aoWeaponId: 41,
  },
  hunting_bow: {
    id: "hunting_bow",
    name: "items.hunting_bow.name",
    slot: "weapon",
    rarity: "common",
    stats: { agi: 5 },
    goldValue: 20,
    requiredClass: ["RANGER"],
    aoWeaponId: 41,
  },
  longbow: {
    id: "longbow",
    name: "items.longbow.name",
    slot: "weapon",
    rarity: "uncommon",
    stats: { agi: 10 },
    goldValue: 65,
    requiredClass: ["RANGER"],
    aoWeaponId: 7,
  },
  elven_bow: {
    id: "elven_bow",
    name: "items.elven_bow.name",
    slot: "weapon",
    rarity: "rare",
    stats: { agi: 18, str: 4 },
    goldValue: 280,
    requiredClass: ["RANGER"],
    aoWeaponId: 28,
  },
  dagger_dual: {
    id: "dagger_dual",
    name: "items.dagger_dual.name",
    slot: "weapon",
    rarity: "common",
    stats: { agi: 3 },
    goldValue: 15,
    requiredClass: ["ROGUE"],
    aoWeaponId: 13,
  },
  twin_daggers: {
    id: "twin_daggers",
    name: "items.twin_daggers.name",
    slot: "weapon",
    rarity: "common",
    stats: { agi: 4, str: 2 },
    goldValue: 22,
    requiredClass: ["ROGUE"],
    aoWeaponId: 12,
  },
  shadow_daggers: {
    id: "shadow_daggers",
    name: "items.shadow_daggers.name",
    slot: "weapon",
    rarity: "uncommon",
    stats: { agi: 9, str: 4 },
    goldValue: 70,
    requiredClass: ["ROGUE"],
    aoWeaponId: 35,
  },
  venom_blades: {
    id: "venom_blades",
    name: "items.venom_blades.name",
    slot: "weapon",
    rarity: "rare",
    stats: { agi: 15, str: 6 },
    goldValue: 260,
    requiredClass: ["ROGUE"],
    aoWeaponId: 11,
  },
  holy_mace: {
    id: "holy_mace",
    name: "items.holy_mace.name",
    slot: "weapon",
    rarity: "common",
    stats: { str: 4, int: 3 },
    goldValue: 25,
    requiredClass: ["CLERIC", "PALADIN"],
    aoWeaponId: 4,
  },
  blessed_hammer: {
    id: "blessed_hammer",
    name: "items.blessed_hammer.name",
    slot: "weapon",
    rarity: "uncommon",
    stats: { str: 8, int: 8 },
    goldValue: 90,
    requiredClass: ["CLERIC", "PALADIN"],
    aoWeaponId: 15,
  },
  elder_staff: {
    id: "elder_staff",
    name: "items.elder_staff.name",
    slot: "weapon",
    rarity: "uncommon",
    stats: { int: 10, hp: 20 },
    goldValue: 75,
    requiredClass: ["CLERIC", "MAGE"],
    aoWeaponId: 20,
  },
  bronze_axe: {
    id: "bronze_axe",
    name: "items.bronze_axe.name",
    slot: "weapon",
    rarity: "common",
    stats: { str: 6 },
    goldValue: 18,
    aoWeaponId: 3,
  },
  iron_dagger: {
    id: "iron_dagger",
    name: "items.iron_dagger.name",
    slot: "weapon",
    rarity: "common",
    stats: { agi: 5 },
    goldValue: 15,
    aoWeaponId: 12,
  },
  bone_sword: {
    id: "bone_sword",
    name: "items.bone_sword.name",
    slot: "weapon",
    rarity: "uncommon",
    stats: { str: 12, agi: 3 },
    goldValue: 95,
    requiredClass: ["WARRIOR", "PALADIN", "ROGUE"],
    aoWeaponId: 21,
  },

  // --- ARMOR ---
  tunic: {
    id: "tunic",
    name: "items.tunic.name",
    slot: "armor",
    rarity: "common",
    stats: { armor: 1 },
    goldValue: 3,
  },
  leather_armor: {
    id: "leather_armor",
    name: "items.leather_armor.name",
    slot: "armor",
    rarity: "common",
    stats: { armor: 3, hp: 10 },
    goldValue: 15,
  },
  chainmail: {
    id: "chainmail",
    name: "items.chainmail.name",
    slot: "armor",
    rarity: "uncommon",
    stats: { armor: 8, hp: 30 },
    goldValue: 50,
    requiredClass: ["WARRIOR", "CLERIC", "PALADIN"],
  },
  plate_armor: {
    id: "plate_armor",
    name: "items.plate_armor.name",
    slot: "armor",
    rarity: "rare",
    stats: { armor: 15, hp: 60, str: 5 },
    goldValue: 200,
    requiredClass: ["WARRIOR", "PALADIN"],
  },
  mage_robes: {
    id: "mage_robes",
    name: "items.mage_robes.name",
    slot: "armor",
    rarity: "common",
    stats: { int: 3, mana: 15 },
    goldValue: 18,
    requiredClass: ["MAGE"],
  },
  shadow_cloak: {
    id: "shadow_cloak",
    name: "items.shadow_cloak.name",
    slot: "armor",
    rarity: "uncommon",
    stats: { agi: 5, armor: 4 },
    goldValue: 60,
    requiredClass: ["ROGUE", "RANGER"],
  },
  vampire_cape: {
    id: "vampire_cape",
    name: "items.vampire_cape.name",
    slot: "armor",
    rarity: "rare",
    stats: { armor: 6, agi: 10, str: 5, hp: 40 },
    goldValue: 350,
    requiredClass: ["ROGUE", "RANGER", "WARRIOR", "MAGE", "CLERIC", "PALADIN"],
  },

  // --- SHIELDS ---
  wooden_shield: {
    id: "wooden_shield",
    name: "items.wooden_shield.name",
    slot: "shield",
    rarity: "common",
    stats: { armor: 2 },
    goldValue: 10,
    aoShieldId: 1,
  },
  iron_shield: {
    id: "iron_shield",
    name: "items.iron_shield.name",
    slot: "shield",
    rarity: "uncommon",
    stats: { armor: 5, hp: 15 },
    goldValue: 35,
    aoShieldId: 2,
  },

  // --- HELMETS ---
  iron_helmet: {
    id: "iron_helmet",
    name: "items.iron_helmet.name",
    slot: "helmet",
    rarity: "common",
    stats: { armor: 2, hp: 8 },
    goldValue: 12,
    aoHelmetId: 1,
  },
  wizard_hat: {
    id: "wizard_hat",
    name: "items.wizard_hat.name",
    slot: "helmet",
    rarity: "common",
    stats: { int: 3, mana: 10 },
    goldValue: 14,
    requiredClass: ["MAGE"],
    aoHelmetId: 4,
  },
  crown_of_thorns: {
    id: "crown_of_thorns",
    name: "items.crown_of_thorns.name",
    slot: "helmet",
    rarity: "rare",
    stats: { int: 8, mana: 30, str: 5 },
    goldValue: 220,
    aoHelmetId: 7,
  },

  // --- ACCESSORIES ---
  ring_of_strength: {
    id: "ring_of_strength",
    name: "items.ring_of_strength.name",
    slot: "ring",
    rarity: "uncommon",
    stats: { str: 5 },
    goldValue: 100,
  },
  ring_of_agility: {
    id: "ring_of_agility",
    name: "items.ring_of_agility.name",
    slot: "ring",
    rarity: "uncommon",
    stats: { agi: 5 },
    goldValue: 100,
  },
  ring_of_intellect: {
    id: "ring_of_intellect",
    name: "items.ring_of_intellect.name",
    slot: "ring",
    rarity: "uncommon",
    stats: { int: 5 },
    goldValue: 100,
  },
  ring_of_vitality: {
    id: "ring_of_vitality",
    name: "items.ring_of_vitality.name",
    slot: "ring",
    rarity: "uncommon",
    stats: { hp: 50 },
    goldValue: 120,
  },
  blood_amulet: {
    id: "blood_amulet",
    name: "items.blood_amulet.name",
    slot: "ring",
    rarity: "rare",
    stats: { hp: 80, str: 8 },
    goldValue: 400,
  },

  // --- CONSUMABLES ---
  health_potion: {
    id: "health_potion",
    name: "items.health_potion.name",
    slot: "consumable",
    rarity: "common",
    stats: {},
    goldValue: 8,
    consumeEffect: { healHp: 50 },
    stackable: true,
  },
  mana_potion: {
    id: "mana_potion",
    name: "items.mana_potion.name",
    slot: "consumable",
    rarity: "common",
    stats: {},
    goldValue: 8,
    consumeEffect: { healMana: 40 },
    stackable: true,
  },
  great_health_potion: {
    id: "great_health_potion",
    name: "items.great_health_potion.name",
    slot: "consumable",
    rarity: "uncommon",
    stats: {},
    goldValue: 25,
    consumeEffect: { healHp: 150 },
    stackable: true,
  },
  great_mana_potion: {
    id: "great_mana_potion",
    name: "items.great_mana_potion.name",
    slot: "consumable",
    rarity: "uncommon",
    stats: {},
    goldValue: 25,
    consumeEffect: { healMana: 120 },
    stackable: true,
  },

  // --- TAMING / MOUNTS ---
  lasso: {
    id: "lasso",
    name: "items.lasso.name",
    slot: "consumable",
    rarity: "common",
    stats: {},
    goldValue: 15,
    stackable: true,
  },
  brown_horse: {
    id: "brown_horse",
    name: "items.brown_horse.name",
    slot: "mount",
    rarity: "uncommon",
    stats: { speedBonus: 4 },
    goldValue: 250,
    mountNpcType: "horse",
  },
  elephant_mount: {
    id: "elephant_mount",
    name: "items.elephant_mount.name",
    slot: "mount",
    rarity: "rare",
    stats: { speedBonus: 3 },
    goldValue: 1200,
    mountNpcType: "elephant",
  },
  dragon_mount: {
    id: "dragon_mount",
    name: "items.dragon_mount.name",
    slot: "mount",
    rarity: "epic",
    stats: { speedBonus: 6 },
    goldValue: 5000,
    mountNpcType: "dragon",
  },
  bear_mount: {
    id: "bear_mount",
    name: "items.bear_mount.name",
    slot: "mount",
    rarity: "uncommon",
    stats: { speedBonus: 3 },
    goldValue: 400,
    mountNpcType: "bear",
  },
};
